### PR TITLE
988 - Fix initialization of pages with a single datepicker

### LINKED ISSUE #988: Can't select date for a goods declaration
In Person > Declarations > New, when trying to select a date for the declaration, I click on the the date selector but it doesn't do anything. No JS error fires.

And if you try to save the declaration, you can't because it doesn't have a date.

### PR DESCRIPTION
**Pull request by amiedes**
Fixes #988

### CODE REVIEW

**Comment by amiedes** [comment]
@ferblape The datepicker initialization code inside `application.js` really needs to be rewritten in a more clear way, but for the time being I'd leave it like this.

File: test/services/gobierto_budget_consultations/csv_exporter_test.rb [hunk 1]
```diff
@@ -16,8 +16,8 @@ def test_export
     csv = @subject.export(consultation)
     assert_equal csv, <<~CSV
       id,age,gender,location,question,answer
-      692345489,35,male,,Pavimentación de vías públicas,-5
-      692345489,35,male,,Inversión en Instalaciones Deportivas,5
+      692345489,36,male,,Pavimentación de vías públicas,-5
```
Comment (ferblape) [inline test/services/gobierto_budget_consultations/csv_exporter_test.rb]: We prefer to fix it in a more resilient way.
