### PR TITLE
2957 append data to table using existing schema

### LINKED ISSUE #2957: Data / Appending data to an existing dataset with custom schema fails
If you create a dataset with a custom schema any other further request to update the dataset (using append option) will overwrite the schema. I'd expect the schema to don't be overwritten by an action that is only updating the data.

Steps to reproduce:

1. define $API_TOKEN_ADMIN env var

2. Create the dataset using a custom schema:

```
ruby $DEV_DIR/gobierto-etl-utils/operations/gobierto_data/upload-dataset/run.rb --api-token $API_TOKEN_ADMIN --gobierto-url http://madrid.gobierto.test --name "Calidad aire" --slug calidad-aire --table-name calidad_aire --csv-separator=';' --file-path=data.csv --schema-path=$DEV_DIR/gobierto-etl-datos/datasets/calidad_del_aire_madrid/schema_create.json
```

3. Update the dataset with today data (using append option):

```
ruby $DEV_DIR/gobierto-etl-utils/operations/gobierto_data/upload-dataset/run.rb --api-token $API_TOKEN_ADMIN --gobierto-url http://madrid.gobierto.test --name "Calidad aire" --slug calidad-aire --table-name calidad_aire --file-path=daily_data.csv --append 
```

In the create statements code the table is created from zero, instead of using the schema of the existing table.

Associated Rollbar: https://rollbar.com/Populate/gobierto/items/3649/

### PR DESCRIPTION
**Pull request by entantoencuanto**
Closes #2957

## :v: What does this PR do?

* Fixes an exception generated when write queries are sent to module database and configuration for queries with writing permissions fails.
* Makes custom schema parsing more flexible to detect custom configuration for CSV columns using a case-insensitive lookup.
* Makes import from CSV dataset method to make use of a custom schema based on existing table columns types when used with append option enabled and no schema configuration is provided.
* Changes the default date format importing from csv to "YYY-MM-DD"
* Allows the omission of `original_name` in schema JSON file. If omitted it's assumed that the 
`original_name` the same as the destination name 
* Adds some tests

## :shipit: Does this PR changes any configuration file?

No

(Changes in these files might need to update the role in Ansible)

## :book: Does this PR require updating the documentation?

No

### CODE REVIEW

**Comment by ferblape** [comment]
Looking good. Let me know when it's available in staging because I need it for a few datasets 🎸

**Comment by entantoencuanto** [comment]
Ready in staging!

**Comment by ferblape** [comment]
Perfect, it works fine. Add some tests and feel free to merge.

File: app/queries/gobierto_data/datasets/creation_statements.rb [hunk 1]
```diff
@@ -57,7 +57,7 @@ def complete_schema_with_defaults(source_file, schema_definition)
         default_schema = inspect_csv_schema(source_file, csv_separator: @csv_separator)
         schema_definition = (schema_definition || {}).deep_symbolize_keys
         default_schema.map do |default_column, default_value|
-          schema_definition.find { |_, value| value[:original_name] == default_value[:original_name] } || [default_column, default_value]
+          schema_definition.find { |_, value| value[:original_name].casecmp?(default_value[:original_name]) } || [default_column, default_value]
```
Comment (ferblape) [inline app/queries/gobierto_data/datasets/creation_statements.rb]: Why the original_name is mandatory? I think it should be optional if the name doesn't change

Comment (entantoencuanto) [reply app/queries/gobierto_data/datasets/creation_statements.rb]: Changed, now this attribute can be omitted
