### PR TITLE
Fix different JS errors

### LINKED ISSUE #2183: Error on comparison chart when the municipality name contains a '
Rollbar: https://rollbar.com/Populate/gobierto/items/1433/

In the budget line comparison chart, when the name of the municipality is converted to an ID for the chart, the single quote is not removed and raises a JS error.

### LINKED ISSUE #2184: `this.init is not a function` JS error
Rollbar: https://rollbar.com/Populate/gobierto/items/1434/

Investigate and fix the error. A customer has just reported the same error.

### LINKED ISSUE #2185: JS errors in data section
Data section doesn't use any Javascript, but causes two JS errors, maybe because we haven't included any JS file, and some basics are required:

- $ is not defined: https://rollbar.com/Populate/gobierto/items/1435/
- I18n is not defined: https://rollbar.com/Populate/gobierto/items/1436/

### PR DESCRIPTION
**Pull request by ferblape**
Closes #2183 
Closes #2184 
Closes #2185 

## :v: What does this PR do?

This PR closes a few errors reported by Rollbar, all of them small things to fix.

## :mag: How should this be manually tested?

- Review no error happens in the bubbles when you resize
- Review no error happens in the budget lines comparison when a municipality has a '
- Review the data section doesn't have any error

### CODE REVIEW

File: test/integration/gobierto_exports/exports_page_test.rb [hunk 1]
```diff
@@ -30,6 +30,21 @@ def test_index
       end
     end
 
+    def test_index_with_javascript
+      with_javascript do
+        with_current_site(site) do
+          with_stubbed_s3_file_upload do
```
Comment (amiedes) [inline test/integration/gobierto_exports/exports_page_test.rb]: Why do we need `with_stubbed_s3_file_upload`? As far as I see the tests in this file only perform read operations, maybe we can remove this block from all the tests in this file?

**Review by amiedes — CHANGES_REQUESTED** [review]

**Comment by ferblape** [comment]
You were rigth, thos stubs aren't unnecessary.
