### PR TITLE
Fix failing test

### LINKED ISSUE #3021: Broken test
There's a broken test in master:

```
GobiertoPeople::People::PersonEventsIndexTest#test_person_events_present_in_other_agendas 
[**************/gobierto/test/integration/gobierto_people/people/person_events_index_test.rb:114]
```

### PR DESCRIPTION
**Pull request by ferblape**
Closes #3021

## :v: What does this PR do?

Fixes JS test and activates a skipped test that seem to work fine.

### CODE REVIEW

File: test/integration/gobierto_people/people/person_events_index_test.rb [hunk 1]
```diff
@@ -99,7 +99,7 @@ def test_events_summary_upcoming_and_past_filters
 
       def test_person_events_present_in_other_agendas
         attributes = {
-          start_date: Time.now.tomorrow,
+          starts_at: Time.now.tomorrow,
```
Comment (ferblape) [inline test/integration/gobierto_people/people/person_events_index_test.rb:102]: It looks like the attribute is starts_at and not start_date

File: test/integration/gobierto_people/people/person_events_index_test.rb [hunk 2]
```diff
@@ -109,33 +109,31 @@ def test_person_events_present_in_other_agendas
         nelson_event.attendees.create(person: richard)
 
         with(site: site, js: true) do
-          visit gobierto_people_person_events_path(richard.slug)
+          visit @path
+
+          click_button "List"
```
Comment (ferblape) [inline test/integration/gobierto_people/people/person_events_index_test.rb:114]: I prefer to test it like the other tests and don't depend on the selector of the calendar

**Review by entantoencuanto — APPROVED** [review]
